### ISSUE TITLE
Shader fails to compile with commit 149bcba

### ISSUE THREAD

**Issue by MSleepyPanda** [servo/webrender#437]
[Commit 149bcba](https://github.com/servo/webrender/commit/149bcba51e345f56e444a0552cd39204ebbb6b90) broke webrender for me, because of shader compilation.

Error:
> Failed to compile shader: "..\\webrender\\webrender\\res\\ps_image_clip.fs.glsl"
> 0(15) : error C1008: undefined variable "pos"
> 0(27) : error C1008: undefined variable "relative_pos_in_rect"

[Commit e9ad82e](https://github.com/servo/webrender/commit/e9ad82efbac1bde805af45e9f2bff4c2792695f4) works, [Commit 149bcba](https://github.com/servo/webrender/commit/149bcba51e345f56e444a0552cd39204ebbb6b90) not, so it is safe to say that it is due to these changes.

OS: Windows 10
Driver: 372.54

**Comment by MSleepyPanda** [comment]
Thanks!
