### ISSUE TITLE
Shader compilation failure in windows/ANGLE

### ISSUE THREAD

**Issue by staktrace** [servo/webrender#1190]
I did a [gecko try push](https://treeherder.mozilla.org/#/jobs?repo=try&revision=faf5f41f5ad5fa2be925358524edc1c6596bcdc1) on windows with webrender enabled, and in the log I saw a bunch of warnings and an error from the shader compilation. This appears to have caused a startup failure and triggered crashes in the test runs. Here's the error output:

```
WebRender - OpenGL version new OpenGL ES 3.0 (ANGLE 2.1.0.dec065540d5f)
...
Failed to link shader program: C:\fakepath(1004,25-35): warning X3556: integer modulus may be much slower, try using uints if possible.
C:\fakepath(1004,41-51): warning X3556: integer divides may be much slower, try using uints if possible.
C:\fakepath(1029,24-35): warning X3556: integer modulus may be much slower, try using uints if possible.
C:\fakepath(1029,41-52): warning X3556: integer divides may be much slower, try using uints if possible.
C:\fakepath(1093,24-35): warning X3556: integer modulus may be much slower, try using uints if possible.
C:\fakepath(1093,41-52): warning X3556: integer divides may be much slower, try using uints if possible.
C:\fakepath(992,24-35): warning X3556: integer modulus may be much slower, try using uints if possible.
C:\fakepath(992,41-52): warning X3556: integer divides may be much slower, try using uints if possible.
C:\fakepath(939,5-16): error X3004: undeclared identifier '_vBorderRect'
Warning: D3D shader compilation failed with default flags. (ps_5_0)
```

I don't remember seeing this error when I last tried this a few weeks ago, and considering the mention of vBorderRect, I'm assuming this regressed with #1087.

**Comment by kvark** [comment]
Dupe of #1157 ?

**Comment by staktrace** [comment]
Looks like it, yeah.
